### ISSUE TITLE
Cannot require org-confluence

### ISSUE THREAD

**Issue by tdehaeze** [hgschmie/org-confluence#1]
Hi,

I have an issue when trying to load org-confluence.
I am using the Doom Emacs configuration, so I have put the following in my config:
```
(package! org-confluence
  :recipe (:host github
           :repo "hgschmie/org-confluence"
           :files ("*.el")))
```

Then when I call `(require 'org-confluence)`, I have the following message: `Cannot open load file: No such file or directory, org-exp`.

I suppose `org-exp` is part of org-mode, but I am not sure how to deal with this issue.

Thanks

**Comment by hgschmie** [comment]
Hi. Wow, that repo is ancient. I don't think I have used that with any recent emacs (and it does not work with current versions of confluence either because they changed the internal format). Yes, org-exp is part of org-mode but I am not sure if that still ships with current emacs.

**Comment by tdehaeze** [comment]
Thanks a lot @hgschmie .
